# Generated by Django 5.2.3 on 2025-06-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('c_type', models.CharField(max_length=10)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('prev', models.TextField(blank=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
